### ISSUE TITLE
Running Gulp throws Requiring external module babel-registererror

### ISSUE THREAD

**Issue by Nahdus** [tcorral/Design-Patterns-in-Javascript#15]
1. Did '''npm install'''

1. Tried running '''gulp '''

**Got the following error**

```
[21:03:57] Requiring external module babel-register
assert.js:341
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (E:\opensource\Design-Patterns-in-Javascript\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (E:\opensource\Design-Patterns-in-Javascript\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (E:/opensource/Design-Patterns-in-Javascript/gulpfile.babel.js:47:6)
    at Module._compile (internal/modules/cjs/loader.js:816:30)
    at loader (E:\opensource\Design-Patterns-in-Javascript\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (E:\opensource\Design-Patterns-in-Javascript\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:685:32)
    at Function.Module._load (internal/modules/cjs/loader.js:620:12)
    at Module.require (internal/modules/cjs/loader.js:723:19)
    at require (internal/modules/cjs/helpers.js:14:16)

E:\opensource\Design-Patterns-in-Javascript>gulp
[21:06:21] Requiring external module babel-register
node:assert:399
    throw err;
    ^

AssertionError [ERR_ASSERTION] [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (E:\opensource\Design-Patterns-in-Javascript\node_modules\undertaker\lib\set-task.js:10:3)
    at Gulp.task (E:\opensource\Design-Patterns-in-Javascript\node_modules\undertaker\lib\task.js:13:8)
    at Object.<anonymous> (E:/opensource/Design-Patterns-in-Javascript/gulpfile.babel.js:47:6)
    at Module._compile (node:internal/modules/cjs/loader:1105:14)
    at loader (E:\opensource\Design-Patterns-in-Javascript\node_modules\babel-register\lib\node.js:144:5)
    at Object.require.extensions.<computed> [as .js] (E:\opensource\Design-Patterns-in-Javascript\node_modules\babel-register\lib\node.js:154:7)
    at Module.load (node:internal/modules/cjs/loader:981:32)
    at Function.Module._load (node:internal/modules/cjs/loader:822:12)
    at Module.require (node:internal/modules/cjs/loader:1005:19)
    at require (node:internal/modules/cjs/helpers:102:18) {
  generatedMessage: false,
  code: 'ERR_ASSERTION',
  actual: false,
  expected: true,
  operator: '=='
}```

**Comment by Nahdus** [comment]
Using node version 16.15,1

**Comment by Painter-Of-Wind** [comment]
same problem

**Comment by yzkkunshao** [comment]
https://github.com/tcorral/Design-Patterns-in-Javascript/issues/15#issue-1297661762
try as below👇:
`nvm` use 8.17.0
then execute `gulp`
The program will run smoothly without any issue
