### ISSUE TITLE
Some compile errors while use `gulp`

### ISSUE THREAD

**Issue by jiechen257** [tcorral/Design-Patterns-in-Javascript#19]
such as:
```shell
[15:37:23] Requiring external module babel-register
ReferenceError: primordials is not defined
    at fs.js:36:5
    at req_ (/Users/abm/Documents/personal/personal-note-v2/Design-Patterns-in-Javascript/node_modules/natives/index.js:143:24)
    at Object.req [as require] (/Users/abm/Documents/personal/personal-note-v2/Design-Patterns-in-Javascript/node_modules/natives/index.js:55:10)
    at Object.<anonymous> (/Users/abm/Documents/personal/personal-note-v2/Design-Patterns-in-Javascript/node_modules/vinyl-fs/node_modules/graceful-fs/fs.js:1:37)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Object.require.extensions.<computed> [as .js] (/Users/abm/Documents/personal/personal-note-v2/Design-Patterns-in-Javascript/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
```

**Comment by jiechen257** [comment]
solutions: check yourt node version, and switch node version to `11.15.0`

for example, use `nvm`
```
rm -rf /node_modules

nvm install 11.15.0

nvm use 11.15.0

npm i

gulp
```

use `npm rebuild node-sass` while encounter gyp errors
